version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - name: Download dependencies
        run: ./gradlew dependencies
      - name: Run tests
        run: ./gradlew test
